const groupMap = {
  Layout: [
    'display',
    'flex',
    'flex-basis',
    'flex-direction',
    'flex-flow',
    'flex-grow',
    'flex-shrink',
    'flex-wrap',
    'align-content',
    'align-items',
    'align-self',
    'justify-content',
    'justify-items',
    'justify-self',

    'visibility',
    'overflow',
    'float',
    'clear',

    'position',
    'top',
    'right',
    'bottom',
    'left',

    'z-index',
  ],
  Box: [
    'width',
    'height',
    'min-width',
    'min-height',
    'max-width',
    'max-height',

    'margin',
    'margin-top',
    'margin-right',
    'margin-bottom',
    'margin-left',
    'margin-block-start',
    'margin-block-end',
    'margin-inline',
    'margin-inline-start',
    'margin-inline-end',

    'padding',
    'padding-top',
    'padding-right',
    'padding-bottom',
    'padding-left',
    'padding-block',
    'padding-block-start',
    'padding-block-end',
    'padding-inline',
    'padding-inline-start',
    'padding-inline-end',

    'outline',
    'outline-offset',
    'outline-width',
    'outline-style',
    'outline-color',

    'border',
    'border-top',
    'border-right',
    'border-bottom',
    'border-left',
    'border-width',
    'border-top-width',
    'border-right-width',
    'border-bottom-width',
    'border-left-width',

    'border-radius',

    'box-shadow',
  ],
  Background: [
    'background',
    'background-attachment',
    'background-clip',
    'background-color',
    'background-image',
    'background-blend-mode',
    'background-origin',
    'background-position',
    'background-repeat',
    'background-size',
  ],
  Font: [
    'color',
    'font-style',
    'font-weight',
    'font-size',
    'line-height',
    'letter-spacing',
    'text-align',
    'text-indent',
    'vertical-align',
    'white-space',
  ],
  Animation: ['animation'],
};

module.exports = {
  plugins: ['stylelint-order'],
  customSyntax: '@stylelint/postcss-css-in-js',
  rules: {
    'declaration-empty-line-before': [
      'always',
      {
        except: ['first-nested'],
        ignore: ['after-comment', 'after-declaration'],
      },
    ],
    'order/order': ['custom-properties', 'declarations'],
    'order/properties-order': [
      Object.keys(groupMap).map(groupName => ({
        groupName: groupName,
        emptyLineBefore: 'threshold',
        noEmptyLineBetween: true,
        properties: groupMap[groupName],
      })),
      {
        unspecified: 'bottomAlphabetical',
        emptyLineBeforeUnspecified: 'threshold',
        emptyLineMinimumPropertyThreshold: 3,
      },
    ],
  },
};
